move some BRs, thus fixing build w/o docs:
ImportError: No module named netaddr
ImportError: No module named yaml
Change-Id: I2ae41f8aaac4dfbbedc52bd391307acc7fafe2c6